"""remove dummy column using autogenerate

Revision ID: ea1b49fee78e
Revises: 77af5b42c924
Create Date: 2023-12-10 18:55:04.504903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1b49fee78e'
down_revision: Union[str, None] = '77af5b42c924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dummy', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
